# Practial Machine Learning - homework

The first step was loading of caret:

```{R}
library(caret)
```

Next, the training set was loaded:

```{R}
training <- read.csv("pml-training.csv", header=T, na=c("NA",""))
```

Then I explored data to check meaning of columns:

```{R}
dim(training)
training$X
table(training$user_name)
plot(training$raw_timestamp_part_1)
plot(training$raw_timestamp_part_2)
plot(training$cvtd_timestamp)
plot(training$new_window)
plot(training$num_window)
table(training$classe)
```

It turned out that columns 1:7 are useless for machine learning, so they were removed:

```{R}
training.filt <- training[,8:ncol(training)]
```

Data contain a lot of missing values, columns with missing values were removed:

```{R}
isna <- is.na(training.filt)
isna.col <- apply(isna, 2, sum)==0
training.pure <- training.filt[,isna.col]
```

The training set was paritioned to "real" training set and in-training validation set (50+50 %):

```{R}
set.seed(666)
train.logical <-createDataPartition(training.pure$classe,p=0.5,list=FALSE)
real.training <- training.pure[train.logical,]
first.testing <- training.pure[-train.logical,]
```

It was trained by Random Forest with a cross-validation:

```{R}
set.seed(667)
rfmod <- train(classe~., data=real.training,
    method="rf", trControl=trainControl(method="cv"))
```

The result was:

```{R}
rfmod
rfmod$finalModel
```

Then I prepared Figure 1:

```{R}
plot(rfmod$finalModel)
```

The outcomes for the in-training validation set were predicted and the confusion matrix was calculated and ploted (Figure 2):

```{R}
first.pred <- predict(rfmod, first.testing)
cm<-confusionMatrix(first.pred, first.testing$classe)
image(1:5, 1:5, cm$table, col=rainbow(100)[70:1], zlim=c(0,3000),
        axes=F, xlab="predicted class", ylab="real class")
axis(1, labels=c("A","B","C","D","E"), at=1:5)
axis(2, labels=c("A","B","C","D","E"), at=1:5)
xpos <- rep(1:5, times=5)
ypos <- rep(1:5, each=5)
text(xpos, ypos, labels=as.vector(cm$table))
```

Next, results were predicted for the test dataset:

```{R}
testing <- read.csv("pml-testing.csv", header=T)
```

Useless lines in the test set were removed:

```{R}
testing.filt <- testing[,8:(ncol(training)-1)]
```

A blank column was added to test set to replace outcomes:

```{R}
blank <- matrix(ncol=1, nrow=20)
testing.filt <- cbind(testing.filt, blank)
```

Misisng data were filterred out and format was checked:

```{R}
testing.pure <- testing.filt[,isna.col]
testing.pure
names(testing.pure)==names(training.pure)
```

Prediction for the test set was done:

```{R}
second.pred <- predict(rfmod, testing.pure)
second.pred
```

